name: 1- Vector Store Update

on:
  workflow_dispatch:

jobs:
  update-vector-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests

      - name: Run Embedding Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: "grains-files"
          S3_PREFIX: "house-keeping/"
          VECTOR_STORE_NAME: "grains-house-keeping"
          PROCESSED_FILES_KEY: "processed/house-keeping.json"
        run: |
          cd ./vector_store
          python embedding.py
